name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "18"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn test
      - run: yarn build
