name: Bump and tag

on:
    push:
        branches:
            - "main"

jobs:
    tag-and-bump:
        if: "!startsWith(github.event.head_commit.message, 'bump:')"
        runs-on: ubuntu-latest
        name: "Bump version and create changelog with commitizen"
        steps:
            - name: Check out
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                token: "${{ secrets.GITHUB_TOKEN }}"
            - id: cz
              name: Bump package
              uses: commitizen-tools/commitizen-action@master
              with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Print Version
              run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
